### ISSUE TITLE
Text is blurry

### ISSUE THREAD

**Issue by ales-tsurko** [pop-os/cosmic-text#106] opened 2023-03-08 14:42 UTC
I'm on macOS 13.2.1, with M1. When I run the `editor-libcosmic` example, the text looks blurry compared to native text. Some time ago I head [this issue](https://github.com/vurtun/nuklear/issues/408) with [`nuklear`](https://github.com/Immediate-Mode-UI/Nuklear). It was related to antialiasing. (Notice also on the screenshot some symbols aren't rendered, but I'm not sure whether it's related to `cosmic-text`.)
<img width="552" alt="Screenshot 2023-03-08 at 17 39 40" src="https://user-images.githubusercontent.com/8686568/223743092-076a26c4-86d3-4ee2-a5d4-52d7240ac6dc.png">

**Comment by jackpot51** [comment] 2023-03-13 14:09
I believe this is an issue with the image renderer in iced, try the editor-orbclient example.

**Comment by ales-tsurko** [comment] 2023-03-14 12:42
It's blurry too:

<img width="457" alt="Screenshot 2023-03-14 at 15 41 14" src="https://user-images.githubusercontent.com/8686568/225004199-5832b66c-917f-4793-8dd6-88a0ee5f8743.png">

**Comment by jackpot51** [comment] 2023-03-18 15:37
I'm going to try making a softbuffer example. I believe this is HiDPI scaling on macOS causing the issue and orbclient is not handling that correctly.

**Comment by VitalyAnkh** [comment] 2023-03-23 04:57
This also happens on Linux with Gnome on Wayland, with a 2560x1600 display. 

Like the image below show, the editor-libcosmic (left side) window's fonts are much blurry than those in firefox (left side).

![image](https://user-images.githubusercontent.com/24508452/227106991-925d2a55-54d7-4dbf-b855-08553b34779f.png)

**Comment by jackpot51** [comment] 2023-03-23 19:53
@VitalyAnkh please see if the orbclient example has the same problem on Linux. I believe there are two different issues here:

- editor-libcosmic rendering in an image that is 1x scale on HiDPI systems
- editor-orbclient not telling macOS it is HiDPI capable

**Comment by jackpot51** [comment] 2023-03-24 13:52
Fixed in the latest commit, for editor-libcosmic. Not fixed for editor-orbclient on macOS, but I recommend the libcosmic example since it uses native macOS rendering.

**Closed** 2023-03-24 13:51 UTC

**Comment by VitalyAnkh** [comment] 2023-03-24 14:39
@jackpot51 Confirmed it's also fixed for editor-libcosmic on Linux with gnome wayland with HiDPI display.  

![image](https://user-images.githubusercontent.com/24508452/227555544-4b0d4b6f-fcca-4b14-a9ac-e3103b157c25.png)


And editor-orbclient is still blurry as you said.

![image](https://user-images.githubusercontent.com/24508452/227555756-1ecdd43b-b0c3-41eb-982e-efc9f26d8922.png)

**Comment by ales-tsurko** [comment] 2023-03-24 20:25
Can confirm it's fixed on macOS.

**Comment by HolgerGottChristensen** [comment] 2023-07-03 19:18
I seem to still have a problem with some of the text being blurry when running the editor-libcosmic example.

The interesting thing is that it seems to only be the text in the editor that is blurry and the rest of the UI is crisp.

<img width="420" alt="Screenshot 2023-07-03 at 21 13 56" src="https://github.com/pop-os/cosmic-text/assets/11473146/f44b207f-10a5-47e7-b2f2-1aa9a7954467">

**Comment by VitalyAnkh** [comment] 2023-07-10 23:03
I experienced the same issue as @HolgerGottChristensen 
![image](https://github.com/pop-os/cosmic-text/assets/24508452/8125a5f2-ffd0-4f1e-b1d9-556c1d93e50e)

**Comment by VitalyAnkh** [comment] 2023-07-10 23:20
After bisecting I found the blur issue of editor-libcosmic originates from https://github.com/pop-os/cosmic-text/commit/f6f56a93be8500fe3b43558730c171f08e5ce5d7. This commit just updated the revision of libcosmic, so the real problem in libcosmic is to be investigated :rocket:

**Comment by mmstick** [comment] 2024-07-30 04:37
@ltrook21 Chrome doesn't use cosmic-text
