### ISSUE TITLE
Cosmic text does not accept numpad input, even when the numpad is enabled

### ISSUE THREAD

**Issue by hfc2x** [pop-os/cosmic-text#341] opened 2024-12-22 01:24 UTC
What it says in the description. I know my Num Lock is enabled, because I can type the following numbers here: 123456789.

These numbers do not get typed into Cosmic Text whatsoever. Instead, I get the inputs for Home, End, PgUp, etc.

**Comment by leviport** [comment] 2024-12-23 16:17
Duplicate of https://github.com/pop-os/cosmic-epoch/issues/730

**Closed by leviport** 2024-12-23 16:17 UTC
